spring.application.name=url-shortener
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/url_db
spring.datasource.username=postgres
spring.datasource.password=rootuser

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379
